---
build: false

clone_folder: c:\gopath\src\github.com\hsmtkk\vigilant-telegram

environment:
  GOPATH: c:\gopath

stack: go 1.17

build_script:
  - go build

test_script:
  - vigilant-telegram.exe
