---
build: false

clone_folder: c:\gopath\src\github.com\$username\$project

environment:
  GOPATH: c:\gopath

stack: go 1.10

debug:
  - cd
  - dir

before_test:
  - go vet ./...

test_script:
  - go test ./...
